[install]
# Only install package versions published at least 3 days ago
minimumReleaseAge = 259200 # seconds
minimumReleaseAgeExcludes = ["@rapideditor/country-coder", "@rapideditor/location-conflation"]

[run]
# equivalent to `bun --bun` for all `bun run` commands
bun = true
shell = "bun"
