import { createRoot } from "react-dom/client";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";
import {
  faSun,
  faMoon,
  faTriangleExclamation,
} from "@fortawesome/free-solid-svg-icons";
import { faGithub } from "@fortawesome/free-brands-svg-icons";

import { Warnings } from "./Warnings";

document.title = "NSI — Wikidata Warnings";

const setDarkMode = (val) => {
  const el = document.getElementById("root");
  if (!el) return;
  if (val === "true") el.classList.add("dark");
  else el.classList.remove("dark");
};

const DarkMode = () => {
  let currValue = window.localStorage.getItem("nsi-darkmode");
  if (currValue === null) {
    if (window.matchMedia("(prefers-color-scheme: dark)").matches) {
      currValue = "true";
      window.localStorage.setItem("nsi-darkmode", currValue);
    }
  }
  setDarkMode(currValue);
  const checkedProp = currValue === "true" ? { defaultChecked: true } : {};

  const toggle = () => {
    const newValue =
      window.localStorage.getItem("nsi-darkmode") === "true" ? "false" : "true";
    window.localStorage.setItem("nsi-darkmode", newValue);
    setDarkMode(newValue);
  };

  return (
    <div id="darkmode" className="control">
      <FontAwesomeIcon icon={faSun} size="lg" />
      <label className="switch">
        <input
          id="nsi-darkmode"
          type="checkbox"
          {...checkedProp}
          onChange={toggle}
        />
        <span className="slider round"></span>
      </label>
      <FontAwesomeIcon icon={faMoon} size="lg" />
    </div>
  );
};

const Header = () => (
  <div id="header" className="hasCols">
    <div id="title">
      <h1>
        <FontAwesomeIcon
          icon={faTriangleExclamation}
          className="hi"
          style={{ color: "#f0b400" }}
        />
        Wikidata Warnings
      </h1>
    </div>
    <div id="nav">
      <a href="index.html">← Back to nsi.guide</a>
    </div>
    <DarkMode />
    <div id="octocat">
      <a
        href="https://github.com/osmlab/name-suggestion-index"
        target="_blank"
        rel="noreferrer"
      >
        <FontAwesomeIcon icon={faGithub} size="2x" />
      </a>
    </div>
  </div>
);

const App = () => (
  <>
    <Header />
    <Warnings />
    <div id="footer">
      Generated by <code>bun run wikidata</code> · See the{" "}
      <a href="https://github.com/osmlab/name-suggestion-index">
        NSI GitHub project
      </a>{" "}
      for details.
    </div>
  </>
);

const root = createRoot(document.getElementById("root"));
root.render(<App />);
