name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  FORCE_COLOR: 2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v7
    - uses: oven-sh/setup-bun@v2
    - name: Install dependencies
      run: bun install
    - name: Remove eslint problem matchers
      run: |
        echo "::remove-matcher owner=eslint-compact::"
        echo "::remove-matcher owner=eslint-stylish::"
    - name: Run all
      run: bun run all
